[package]
name = "poot_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
noise = "0.9.0"
ash = "0.38.0"
bytemuck = "1.17.1"
tokio = { version = "1.40.0", features = ["full"] }

[profile.dev]
debug = true

[profile.release]
debug = true
